version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade awscli

  build:
    commands:
      - echo "Starting build process..."
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://cloudformation/aws-pipeline.yml

  post_build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --stack-name my-data-pipeline-stack \
          --template-file cloudformation/aws-pipeline.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset
      - echo "Build and deployment completed!"
